module.exports = {
    easy: [
      "in the quiet forest the gentle breeze rustles through the leaves creating a soothing melody that embraces all living creatures a stream softly flows providing refreshment to the thirsty animals birds sing their melodious tunes filling the air with harmony and joy the sun's warm rays filter through the treetops illuminating the greenery below amidst this tranquil scene nature's beauty unfolds and a sense of peace envelopes every being present",
      "the moonlight dances upon the calm waters of the lake reflecting its ethereal glow the night is adorned with twinkling stars that seem to whisper ancient secrets the nocturnal creatures emerge from their slumber to explore the darkness nature's nocturne plays out in a symphony of sights and sounds an enchanting world illuminated by the moon's gentle touch",
      "in the meadow wildflowers sway gracefully in the gentle breeze their vibrant colors painting a beautiful tapestry on the green canvas of the earth butterflies flutter and bees hum a delightful orchestra of nature's orchestra the sun like a benevolent artist strokes the landscape with its warm brush creating a masterpiece that captivates all who behold it",
      "across the vast savannah the golden grasses sway with the rhythm of the wind the sun sets painting the horizon in hues of orange and pink as the day bids farewell to the night the silhouettes of animals roam gracefully their silvery eyes shining like stars in the twilight the heartbeat of the savannah echoes with the cycle of life a timeless dance of survival and harmony",
      "deep within the forest ancient trees stand tall and proud their roots firmly grounded in the soil generations of life have thrived in this verdant sanctuary the air is filled with the earthy scent of moss and leaves and the symphony of chirping insects and singing birds provides a comforting melody nature's cathedral where serenity and wonder converge in harmonious unity"
    ],
  medium: [
    "the quick brown fox jumps over the lazy Dog. it is a beautiful sUnny Day and the sKy is clear. i wondEr what adVentures await us. life is full of suRpRises, and we must embrace them all. let's eNjoy every moment and make the most of it. be kind, be Bold, and spread love Everywhere. happiness is found in the simplest of things. cherish those who bring joy into your life, and don't forget to smile. the world is vast, and there is so much to expLore. let's embark on this journey together, hand in hand, and create wonderful memories",
    "The sun rises over the horizon, painting the sky with hues of orange and pink. Birds chirp, welcoming the new day, while the world awakens from its slumber. It's a fresh start, a chance to seize opportunities and overcome challenges. Let's embrace the morning with a smile, ready to make the most of this gift of life. As the day unfolds, let's cherish every moment and be grateful for the experiences that shape us.",
    "Life is a journey of twists and turns. We face peaks of triumphs and valleys of struggles. Through it all, we grow and evolve, becoming stronger versions of ourselves. The lessons we learn and the people we meet leave lasting impressions on our hearts. Let's navigate this adventure with courage and grace, knowing that each step brings us closer to the person we are destined to be. Embrace the uncertainties, for they are the threads that weave the tapestry of our lives.",
    "Love is a force that transcends boundaries. It unites hearts, bridges gaps, and brings joy to those who embrace it. Love can be tender and gentle, yet also fierce and unyielding. It's a language that doesn't require words, for it speaks through actions and emotions. Let's cultivate love within ourselves and share it generously with others. In doing so, we create ripples of positivity that touch lives and make the world a brighter place.",
    "In the depths of silence, we find tranquility. Away from the cacophony of the world, we discover a space to introspect and find peace within ourselves. Meditation allows us to tap into our inner wisdom and connect with the essence of existence. Let's take moments each day to meditate, to be still, and to listen to the whispers of our soul. In this serene state, we may find answers to the questions that elude us amidst the noise of daily life."
  ],
  hard: [
    "Guitar Songs is the second extended play by American singer-songwriter Billie Eilish. Written by Eilish and Finneas O'Connell (both pictured), it was released through download and streaming services on July 21, 2022, as a surprise. Eilish decided on the surprise release because she wanted to share new music with her fans as soon as she could. Guitar Songs consists of two realist sentimental ballads, combining simple acoustic guitars that emphasize Eilish's soft vocal performance with personal lyrics that derive from contemporary life events. One of the tracks, \"The 30th\", is titled after the day of a friend's near-fatal car crash: November 30, 2021. In the lyrics, Eilish ponders over whether the friend would have survived had some circumstances in the accident been different. The other track, \"TV\", discusses eating disorders, disillusionment, and a desire for numbness to distract oneself from pressing world issues.",
    "Flooding and landslides in South Korea (pictured) leave at least 40 people dead and 6 others missing. In the United States, actors in the SAG-AFTRA trade union go on strike, joining writers in the Writers Guild of America strike. Flooding and landslides in northern India leave at least 100 people dead. Czech-French writer Milan Kundera dies at the age of 94. In the Netherlands, the governing coalition collapses and Prime Minister Mark Rutte announces his upcoming resignation.",
    "The Japanese sports anime television series Yuri on Ice had a total of 12 episodes. The series first premiered on TV Asahi on October 6, 2016, and finished airing on December 22, 2016. It was produced by MAPPA, directed by Sayo Yamamoto and written by Mitsurou Kubo. The character designs were by Tadashi Hiramatsu, and the music was composed by Taro Umebayashi and Taku Matsushiba. The series revolves around the relationships between Japanese figure skater Yuri Katsuki, also known as Yuri K., his idol, Russian figure-skating champion Victor Nikiforov, and up-and-coming Russian skater Yuri Plisetsky, also known as Yuri P. The series was made available for streaming by Crunchyroll shortly after its broadcast in Japan, and then Funimation provided an English dub of the series, starting on October 24, 201",
    "Jeanette Scissum is an American mathematician, space scientist, and diversity advocate. Born in Guntersville, Alabama, she gained bachelor's and master's degrees in mathematics at Alabama A&M University. After a brief teaching career, Scissum joined NASA's Marshall Space Flight Center in 1964, as an entry-level mathematician, the first African-American mathematician to be employed there. Her career achievements included techniques for improved forecasting of the sunspot cycle and leading activities in Marshall's Atmospheric, Magnetospheric, and Plasmas in Space project. After returning to Alabama A&M to complete a PhD, Scissum worked at the Goddard Space Flight Center as a computer systems analyst. This NASA photograph shows Scissum at her desk at Marshall Space Flight Center in the 1960s or 1970s."
  ]
}
